core/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


urlpatterns = [
    path("library/", include("library.urls")),
    path("courses/", include("courses.urls")),
    path("control/", include("control.urls")),
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

# Servindo os arquivos de mídia e estáticos
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path
from .views import (
    home,
    about,
    dashboard,
    deleteBook,
    bookDetails,
    manageBook,
    readBook,
    add_suggestion,
    add_comment,
    search_for_books,
)

urlpatterns = [
    path("", home, name="home"),
    path("dashboard/", dashboard, name="dashboard"),
    path("about/", about, name="about"),
    path("book/add/", manageBook, name="books-add"),
    path("book/<slug:slug>/edit/", manageBook, name="books-edit"),
    path("book/<slug:slug>/delete/", deleteBook, name="books-delete"),
    path("book/<slug>/<isbn>/", bookDetails, name="books-details"),
    path("read/<slug>/<isbn>/", readBook, name="read-book"),
    path("add-comment/", add_comment, name="add-comment"),
    path("add-suggestion/", add_suggestion, name="add-sugestion"),
    path("search-for-books/", search_for_books, name="search-for-books"),
]

library/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from colorfield.fields import ColorField

# TODO: add doc


class Author(models.Model):
    photo = models.ImageField(
        verbose_name="Foto", upload_to="author-photos/", null=True, blank=True
    )

    first_name = models.CharField(
        verbose_name="Primeiro Nome", max_length=150, blank=True, null=True
    )

    last_name = models.CharField(
        verbose_name="Sobrenome", max_length=150, blank=True, null=True
    )

    biography = models.TextField(verbose_name="Biografia", null=True, blank=True)

    birth_date = models.DateField(
        verbose_name="Data de Nascimento", blank=True, null=True
    )

    death_date = models.DateField(verbose_name="Data de Óbito", blank=True, null=True)

    addition_date = models.DateTimeField(
        verbose_name="Data de adição",
        auto_now_add=True,
        editable=False,
        blank=False,
        null=False,
    )

    slug = models.SlugField(blank=True, null=True, unique=True)

    @property
    def get_full_name(self):
        return f"{self.first_name.strip().title()} {self.last_name.strip().title()}".strip()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.get_full_name.lower())

        super().save(*args, **kwargs)

    def __str__(self):
        return self.get_full_name


class Publisher(models.Model):
    photo = models.ImageField(
        verbose_name="Foto", upload_to="publisher-photos", null=True, blank=True
    )
    name = models.CharField(verbose_name="Nome", max_length=255, unique=True)
    website = models.URLField(verbose_name="Website", blank=True, null=True)
    address = models.CharField(
        verbose_name="Endereço", max_length=50, blank=True, null=True
    )
    description = models.TextField(
        verbose_name="Descrição", blank=True, null=True, max_length=150
    )

    def __str__(self):
        return self.name


# Better input a Multiple Choices Category in Book, it making it difficult to work
class Category(models.Model):
    name = models.CharField(
        verbose_name="Nome", max_length=100, unique=True, blank=False, null=False
    )
    color = ColorField(default="#efefef", null=True, blank=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    LANGUAGE_CHOICES = [
        ("PT", "Português"),
        ("EN", "Inglês"),
    ]

    cover = models.ImageField(
        verbose_name="Capa", upload_to="cover-photos/", null=True, blank=True
    )

    title = models.CharField(
        verbose_name="Título", max_length=255, blank=False, null=False
    )

    authors = models.ManyToManyField(
        to=Author,
        related_name="books",
    )

    summary = models.TextField(verbose_name="Resumo", null=True, blank=True)

    isbn = models.CharField(verbose_name="ISBN", unique=True, max_length=13)

    publisher = models.ForeignKey(
        to=Publisher, related_name="books", on_delete=models.CASCADE
    )

    categories = models.ManyToManyField(
        to=Category,
        related_name="books",
    )

    publication_date = models.CharField(
        max_length=50, verbose_name="Data de Publicação", blank=True, null=True
    )

    document = models.FileField(
        verbose_name="Documento", upload_to="books/", null=True, blank=True
    )

    created_at = models.DateTimeField(
        verbose_name="Data de criação", auto_now_add=True, editable=False
    )

    language = models.CharField(
        verbose_name="Idioma", max_length=2, choices=LANGUAGE_CHOICES, default="PT"
    )

    pages = models.PositiveIntegerField(verbose_name="Páginas", null=True, blank=True)

    edition = models.PositiveIntegerField(
        verbose_name="Edição",
        null=True,
        blank=True,
        default=1,
        help_text="Por padrão o sistema registra como a primeira edição livro",
    )

    slug = models.SlugField(unique=True, max_length=255, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify({self.title})
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class BookExtraImage(models.Model):
    book = models.ForeignKey(
        Book, related_name="extra_images", on_delete=models.CASCADE
    )
    img = models.ImageField(upload_to="book-extra-images/", null=True, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)


class Sugestion(models.Model):
    user = models.ForeignKey(
        verbose_name="sugestions", to=User, on_delete=models.CASCADE
    )
    text = models.TextField(verbose_name="Sugestão", max_length=500)
    date_sugested = models.DateTimeField(verbose_name="data", auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} ({self.date_sugested})"


class Comment(models.Model):
    user = models.ForeignKey(
        User,
        related_name="books_comment",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    book = models.ForeignKey(Book, related_name="comments", on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        ordering = ("-created_at",)

library/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.contrib.auth import get_user
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.http import require_http_methods

from .forms import BookForm
from .models import Author, Book, Category, Publisher, Sugestion, Comment

from django.http import HttpResponse


def home(request):
    ctx = {}
    template_name = "library/home.html"
    books = Book.objects.all()

    # I'll solve this later
    # if request.method == "GET":
    #     search_book = request.GET.get('search')
    #     if search_book != None:
    #         if books.filter(title__contains=search_book).exists():
    #             books = books.filter(title__contains=search_book)
    #         # elif books.filter(categories__contains=search_book).exists():
    #         #     books = books.filter(categories__contains=search_book) -> Error in MenyToMeny field, I hate this Relation from django

    ctx["books"] = books
    return render(request, template_name, ctx)


@login_required
def dashboard(request):
    ctx = {}
    template_name = "library/dashboard.html"

    if not request.user.is_staff:
        messages.info(request, "Você não tem permissão para acessar essa página")
        return redirect("home")

    books = Book.objects.all()
    sugestions = Sugestion.objects.all()

    ctx.update(
        {
            "books": books,
            "sugestions": sugestions,
            "total_books": books.count(),
            "total_authors": Author.objects.count(),
            "total_categories": Category.objects.count(),
            "total_publishers": Publisher.objects.count(),
        }
    )
    return render(request, template_name, ctx)


@login_required
@require_http_methods(["DELETE"])
def deleteBook(request, slug):
    ctx = {}
    partial_name = "partials/dashboard-table-books.html"

    book = get_object_or_404(Book, slug=slug)
    book.delete()

    ctx["books"] = Book.objects.all()

    messages.success(request, "Livro deletado com sucesso!")
    return render(request, partial_name, ctx)


@login_required
def manageBook(request, slug=None):
    if slug:
        book_instance = get_object_or_404(Book, slug=slug)
    else:
        book_instance = None

    if request.method == "POST":
        form = BookForm(data=request.POST, instance=book_instance, files=request.FILES)

        if form.is_valid() and form.is_multipart():
            form.save()
            action = "criado" if not book_instance else "atualizado"
            messages.success(request, f"O livro foi {action} com sucesso.")
            return redirect("home")
        else:
            messages.error(
                request, "Erro ao salvar o livro. Verifique os dados e tente novamente."
            )

    else:
        form = BookForm(instance=book_instance)

    ctx = {
        "form": form,
        "title": "Adicionar Livro" if not book_instance else "Editar Livro",
    }
    return render(request, "library/book-add.html", ctx)


def bookDetails(request, slug, isbn):
    ctx = {}
    template_name = "library/book-details.html"
    book = get_object_or_404(Book, slug=slug, isbn=isbn)

    ctx["book"] = book
    return render(request, template_name, ctx)


@login_required
@require_http_methods(["POST"])
def add_suggestion(request):
    try:
        data = json.loads(request.body)
        text = data.get("content")

        if not text:
            raise ValueError("O texto não pode estar vazio")

        Sugestion.objects.create(text=text, user=request.user)

        return JsonResponse({}, status=200)
    except Exception as error:
        return JsonResponse({"error": error}, 400)


@login_required
@require_http_methods(["POST"])
def add_comment(request):
    data = json.loads(request.body)
    book_slug = data.get("book_slug")
    content = data.get("content")

    if not content:
        return JsonResponse({"error": "no content"}, status=400)

    if not book_slug:
        return JsonResponse({"error": "no book_slug"}, status=400)

    book = get_object_or_404(Book, slug=book_slug)
    user = get_user(request)

    comment = Comment.objects.create(user=user, book=book, content=content)

    return JsonResponse(
        {
            "userId": comment.user.id,
            "username": comment.user.username,
            "book": comment.book.slug,
            "content": comment.content,
            "created_at": naturaltime(comment.created_at),
        },
        status=201,
    )


@login_required
@xframe_options_exempt
def readBook(request, slug, isbn):
    ctx = {}
    template_name = "library/read.html"
    book = get_object_or_404(Book, slug=slug, isbn=isbn)

    ctx["book"] = book
    return render(request, template_name, ctx)


@require_http_methods(["GET"])
def search_for_books(request):
    query = request.GET.get('q')
    
    books = Book.objects.filter(title__icontains=query).values(
        "id", "title", "isbn", "slug"
    )
    return JsonResponse(list(books), safe=False)

def about(request):
    template_name = "library/about.html"
    ctx = {}

    return render(request, template_name, ctx)

templates/library/book-add.html
{% extends 'bases/library.html' %}
{% load static %}
{% load compress %}
{% block title %}
    {{ title }}
{% endblock title %}
{% block head %}
    {% compress css %}
        <link rel="stylesheet" href="{% static 'css/library/book-details.css' %}">
    {% endcompress %}
{% endblock %}
{% block content %}
    <main style="display: flex;
                 justify-content: center;
                 align-items: center;
                 margin-top: 30px">
        <div style="width: 50rem;" class="bg-white rounded-lg shadow-lg p-6">
            <form method="post" enctype="multipart/form-data">
                {% include 'partials/forms_errors.html' %}
                {% csrf_token %}
                <h2 class="text-xl font-semibold text-gray-800 mb-4">{{ title }}</h2>
                <div style="display: flex; justify-content: space-between;">
                    <div class="flex-1 space-y-4" style="width: 50%;">
                        <div class="mb-4">
                            <label for="title" class="block text-sm font-medium text-gray-700">Título</label>
                            {{ form.title }}
                        </div>
                        <!-- Capa e Arquivo do Livro -->
                        <div class="flex-1">
                            <label for="cover" class="block text-sm font-medium text-gray-700">Capa do Livro</label>
                            {{ form.cover }}
                        </div>
                        <!-- Editora, Idioma e Data de Publicação -->
                        <div class="flex space-x-4 mb-4">
                            <div class="flex-1">
                                <label for="publisher" class="block text-sm font-medium text-gray-700">Editora</label>
                                {{ form.publisher }}
                            </div>
                            <div class="flex-1">
                                <label for="language" class="block text-sm font-medium text-gray-700">Idioma</label>
                                {{ form.language }}
                            </div>
                        </div>
                        <!-- Edição e Número de Páginas -->
                        <div class="flex space-x-4 mb-4">
                            <div class="flex-1">
                                <label for="edition" class="block text-sm font-medium text-gray-700">Edição</label>
                                {{ form.edition }}
                            </div>
                            <div class="flex-1">
                                <label for="pages" class="block text-sm font-medium text-gray-700">Número de Páginas</label>
                                {{ form.pages }}
                            </div>
                        </div>
                        <!-- Autores e Categorias -->
                        <div class="flex space-x-4 mb-4">
                            <div class="flex-1">
                                <label for="authors" class="block text-sm font-medium text-gray-700">Autores</label>
                                {{ form.authors }}
                            </div>
                            <div class="flex-1">
                                <label for="id_categories" class="block text-sm font-medium text-gray-700">Categorias</label>
                                <div class="mt-1">{{ form.categories }}</div>
                            </div>
                        </div>
                    </div>
                    <!-- Segunda coluna de campos -->
                    <div style="width: 50%;
                                border-left: 2px solid #EFEFEF;
                                margin-left: 20px"
                         class="pl-4 space-y-4">
                        <div class="flex-1">
                            <label for="isbn" class="block text-sm font-medium text-gray-700">ISBN</label>
                            {{ form.isbn }}
                        </div>
                        <div class="flex-1">
                            <label for="document" class="block text-sm font-medium text-gray-700">Arquivo do Livro</label>
                            {{ form.document }}
                        </div>
                        <div class="flex-1">
                            <label for="summary" class="block text-sm font-medium text-gray-700">Resumo</label>
                            {{ form.summary }}
                        </div>
                        <div class="flex-1">
                            <label for="publication_date"
                                   class="block text-sm font-medium text-gray-700">
                                Data de
                                Publicação
                            </label>
                            {{ form.publication_date }}
                        </div>
                    </div>
                </div>
                <!-- Botões -->
                <div class="flex justify-end space-x-2 mt-4">
                    <a href="{% url 'dashboard' %}"
                       class="px-4 py-2 bg-gray-300 text-gray-700 rounded hover:bg-gray-400">Cancelar</a>
                    <button type="submit"
                            class="px-4 py-2 bg-[#3DB1C8] text-white rounded hover:bg-blue-600">Confirmar</button>
                </div>
            </form>
        </div>
    </div>
</main>
{% endblock %}

templates/library/book-details.html
{% extends 'bases/library.html' %}
{% load static %}
{% load compress %}
{% load humanize %}
{% block title %}{{ book.title }}{% endblock %}
{% block head %}
    {% compress css %}
        <link rel="stylesheet"
              href="{% static 'libs/node_modules/bootstrap-icons/font/bootstrap-icons.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/library/book-details.css' %}" />
    {% endcompress %}
{% endblock %}
{% block content %}
    <main id="book-details">
        <div class="container">
            <div class="book-cover">
                <div style="width: 100%;display: flex;justify-content: center;">
                    <img src="{{ book.cover.url }}" alt="{{ book.title }}" id="cover" />
                </div>
                <br />
                <hr />
                <div class="extra-images">
                    {% for extra_img in book.extra_images.all %}<img src="{{ extra_img.img.url }}" alt="Extra Image">{% endfor %}
                </div>
            </div>
            <div class="book-layout">
                <div class="book-info">
                    <h1 class="book-title">{{ book.title }}</h1>
                    <p class="book-author">
                        by
                        {% for author in book.authors.all %}
                            <a href="" class="author_link">{{ author.get_full_name }}</a>
                            {% if not forloop.last %},{% endif %}
                        {% endfor %}
                    </p>
                    <div style="display: flex;
                                justify-content: space-between;
                                align-items: center">
                        <div class="book-rating" style="margin-top: 10px;margin-bottom:15px;">
                            {% for category in book.categories.all %}
                                <span class="badge"
                                      style="background-color: {{ category.color }}"
                                      onmouseover="this.style.transform='scale(1.1)'"
                                      onmouseout="this.style.transform='scale(1)'">{{ category.name }}</span>
                            {% endfor %}
                        </div>
                        <div class="book-read" style="margin-top: 10px;margin-bottom:15px;">
                            <a href="{% url 'read-book' slug=book.slug isbn=book.isbn %}">
                                <button class="bn53">
                                    <span>Ler
                                    Livro</span>
                                </button>
                            </a>
                        </div>
                    </div>
                    <hr />
                    <p class="book-summary">{{ book.summary }}</p>
                    <hr />
                    <div class="book-details">
                        <div class="detail">
                            <span>Data de Publicação</span>
                            <i class="bi bi-calendar2-week"></i>
                            <span class="detail-value">{{ book.publication_date }}</span>
                        </div>
                        <div class="detail">
                            <span>Idioma</span>
                            <i class="bi bi-globe-americas"></i>
                            <span class="detail-value">{{ book.get_language_display }}</span>
                        </div>
                        <div class="detail">
                            <span>Páginas</span>
                            <i class="bi bi-file-earmark-text"></i>
                            <span class="detail-value">{{ book.pages }}</span>
                        </div>
                        <div class="detail">
                            <span>Editora</span>
                            <i class="bi bi-buildings"></i>
                            <span class="detail-value">{{ book.publisher.name }}</span>
                        </div>
                        <div class="detail">
                            <span>ISBN-13</span>
                            <i class="bi bi-upc-scan"></i>
                            <span class="detail-value">{{ book.isbn }}</span>
                        </div>
                    </div>
                </div>
            </div>
            {% if request.user.is_authenticated %}
                <div class="comments">
                    <h1>Comentários</h1>
                    <hr />
                    <div class="comment-input">
                        <input type="hidden" id="csrf_token" value="{{ csrf_token }}">
                        <input type="text"
                               placeholder="Escreva um comentário..."
                               id="js-comment-input" />
                        <button class="submit-btn">Enviar</button>
                    </div>
                    <hr />
                    <div id="js-comments">
                        {% for comment in book.comments.all %}
                            <div class="comment">
                                <div class="comment-info">
                                    <h3 class="comment-author">{{ comment.user.username }}</h3>
                                    <span style="color: gray;">{{ comment.created_at|naturaltime }}</span>
                                </div>
                                <p class="comment-text">{{ comment.content }}</p>
                            </div>
                        {% empty %}
                            <div style="text-align: center;
                                        color: gray;
                                        margin-top: 2rem"
                                 id="no-comments">Sem comentários até agora.</div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        </div>
    </main>
    {% compress js %}
        <script>
            function formatTime(timestamp) {
                const now = new Date();
                const date = new Date(timestamp);
                const diffInSeconds = Math.floor((now - date) / 1000);

                if (diffInSeconds < 60) {
                    return `há ${Math.abs(diffInSeconds)} segundos`;
                }

                const diffInMinutes = Math.floor(diffInSeconds / 60);
                if (diffInMinutes < 60) {
                    return `há ${Math.abs(diffInMinutes)} minutos`;
                }

                const diffInHours = Math.floor(diffInMinutes / 60);
                if (diffInHours < 24) {
                    return `há ${Math.abs(diffInHours)} horas`;
                }

                const diffInDays = Math.floor(diffInHours / 24);
                if (diffInDays === 1) {
                    return "ontem";
                } else if (diffInDays < 30) {
                    return `há ${Math.abs(diffInDays)} dias`;
                }

                return date.toLocaleDateString("pt-PT");
            }

            function update_time(timestamp, elementId) {
                function update() {
                    const formattedTime = formatTime(timestamp);
                    const element = document.querySelector(`#comment-${elementId}`);
                    if (element) {
                        element.innerText = formattedTime;
                    }
                }
                update(); // Atualiza imediatamente ao inserir o comentário
                setInterval(update, 30000); // Atualiza a cada 30 segundos
            }

            const ws = new WebSocket(`ws://${window.location.host}/ws/comment-consumer/{{ book.slug }}/`)

            ws.onmessage = (event) => {
                const data = JSON.parse(event.data)

                console.log(data)

                const p = document.querySelector("#no-comments")

                if (p) {
                    p.remove()
                }

                document.querySelector('#js-comments')
                    .insertAdjacentHTML('afterbegin', `
                        <div class="comment">
                            <div class="comment-info">
                            <h3 class="comment-author" data-user-id="${data.userId}">${data.username}</h3>
                            <span style="color: gray;" id="comment-${data.id}">${formatTime(data.created_at)}</span>
                            </div>
                            <p class="comment-text">${data.content}</p>
                        </div>
                    `)
                update_time(data.created_at, data.id);
            }

            document.querySelector('.submit-btn')
                .addEventListener('click', function() {
                    const commentInput = document.querySelector('#js-comment-input');
                    const content = commentInput.value.trim();

                    if (!content) {
                        alert("O comentário não pode estar vazio.");
                        return;
                    }

                    commentInput.value = "";

                    ws.send(JSON.stringify({
                        content: content
                    }))

                })
        </script>
    {% endcompress %}
{% endblock %}

templates/library/read.html
{% extends 'bases/control.html' %}
{% load static %}
{% load compress %}
{% block title %}
  {{ book.title }}
{% endblock %}
{% block head %}
  {% compress css %}
  <link rel="stylesheet" href="{% static 'css/library/home.css' %}" />
  <link rel="stylesheet" href="{% static 'css/library/read.css' %}" />
  {% endcompress %}
  {% compress js %}
      <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js"></script>
  <script src="{% static 'libs/node_modules/sweetalert2/dist/sweetalert2.all.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'libs/node_modules/@fontawesome/fontawesome-free/css/all.min.css' %}" />
  {% endcompress %}
{% endblock %}
{% block content %}
  <div class="reader-container">
    <div class="reader-header">
      <h2 class="book-title">{{ book.title }}</h2>
      <div class="time-stop">
        <div id="timer">00:00</div>
        <button id="stop-reading"><i class="fa-solid fa-stop" style="font-size: 25px;"></i></button>
      </div>
    </div>
    <div class="pdf-container">
      <canvas id="pdf-render"></canvas>
    </div>
    <div class="nav-buttons">
      <button onclick="prevPage()"><i class="fas fa-arrow-left"></i></button>
      <div id="page-info">
        <span id="current-page">1</span> de <span id="total-pages">?</span>
      </div>
      <button onclick="nextPage()"><i class="fas fa-arrow-right"></i></button>
    </div>
  </div>
  {% compress js %}
  <script>
    const url = '{{ book.document.url }}'
    const slug = '{{ book.slug }}'
    const isbn = '{{ book.isbn }}'
  </script>
  <script src="{% static 'js/library/read.js' %}"></script>
  {% endcompress %}
{% endblock %}

templates/library/sugestion-form.html
{% extends 'bases/library.html' %}
{% load static %}
{% load compress %}
{% block title %}
    Sugerir
{% endblock title %}
{% block head %}
    {% compress css %}
        <link rel="stylesheet" href="{% static 'css/library/book-details.css' %}">
        <link rel="stylesheet" href="{% static 'css/library/sugestion.css' %}">
    {% endcompress %}
{% endblock %}
{% block content %}
    <main style="display: flex;
                 justify-content: center;
                 align-items: center;
                 margin-top: 30px">
        <div style="width: 50rem;" class="bg-white rounded-lg shadow-lg p-6">
            <form method="POST" action="{% url 'sugestion' %}">
                {% include 'partials/forms_errors.html' %}
                {% csrf_token %}
                <h2 class="text-xl font-semibold text-gray-800 mb-4">{{ title }}</h2>
                <div style="display: flex; justify-content: space-between;">
                    <div class="flex-1 space-y-4" style="width: 50%;">
                        <div class="mb-4">
                            <label for="title" class="block text-sm font-medium text-gray-700">Assunto</label>
                            {{ forms.about }}
                        </div>
                        <!-- Capa e Arquivo do Livro -->
                        <div class="flex-1">
                            <label for="cover" class="block text-sm font-medium text-gray-700">Sugestão</label>
                            {{ forms.sugestion }}
                        </div>
                        <!-- Botões -->
                        <div class="flex justify-end space-x-2 mt-4">
                            <a href="{% url 'home' %}"
                               class="formbold-btn px-4 py-2 bg-gray-300 text-gray-700 rounded hover:bg-gray-400">
                                Cancelar
                            </a>
                            <button type="submit"
                                    class="formbold-btn px-4 py-2 bg-[#3DB1C8] text-white rounded hover:bg-[#3DB1C8] transition-transform duration-300 transform">
                                Enviar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
{% endblock %}